export const idAndPhrasesMap: { [key: number]: string } = {
    1: "Wishing you a day full of smiles and sunshine!",
    2: "Have an amazing walk today and enjoy the fresh air!",
    3: "Here's to a day filled with joy and laughter!",
    4: "May your day be as bright as your smile!",
    5: "Enjoy every moment today, have fun!",
    6: "Wishing you a delightful day full of happiness!",
    7: "Hope today brings you a lot of fun and excitement!",
    8: "Have a wonderful day ahead, make the most of it!",
    9: "Sending you good vibes for a fantastic day!",
    10: "May your day be filled with positive energy and happiness!",
    11: "Here's to a bright and joyful day for you!",
    12: "Wishing you an awesome day full of adventure!",
    13: "May today bring you a reason to smile every hour!",
    14: "Have a day as lovely as you are!",
    15: "Take a deep breath and enjoy your walk today!",
    16: "May your day be filled with pleasant surprises and smiles!",
    17: "Sending you happiness for a fantastic and productive day!",
    18: "Wishing you a fun and carefree day!",
    19: "Here’s to a day of peace and happiness!",
    20: "Wishing you a beautiful day full of possibilities!",
    21: "Have a great day filled with joy and laughter!",
    22: "May today bring you peace, love, and happiness!",
    23: "Sending you a big smile to start your day right!",
    24: "Hope your day is filled with positive vibes and good moments!",
    25: "Enjoy every moment, today is yours to shine!",
    26: "Wishing you a day full of sunshine and happiness!",
    27: "May today bring you unexpected joy and endless smiles!",
    28: "Here’s to a day as beautiful as your spirit!",
    29: "Wishing you a fun-filled day full of happy surprises!",
    30: "May your day be bright and your mood even brighter!",
    31: "Have a cheerful day, filled with fun and laughter!",
    32: "Wishing you a peaceful and joyful day ahead!",
    33: "Hope today is full of little things that make you smile!",
    34: "Take a deep breath and enjoy the beauty of today!",
    35: "May your day be as positive as your mindset!",
    36: "Wishing you a magical day filled with love and happiness!",
    37: "Here’s to a day that’s as kind to you as you are to others!",
    38: "May today bring you all the fun and laughter you deserve!",
    39: "Wishing you a lovely day filled with happiness and success!",
    40: "Take a moment to enjoy the little joys of today!",
    41: "May your day be filled with unexpected moments of joy!",
    42: "Here’s to a calm and peaceful day full of happy thoughts!",
    43: "Wishing you a fun and adventurous day ahead!",
    44: "May today bring you the happiness you give to others!",
    45: "Enjoy the beauty of today and the love that surrounds you!",
    46: "Sending you a cheerful smile for a bright and joyful day!",
    47: "Hope today fills you with energy and good vibes!",
    48: "May today be full of beautiful moments and happy memories!",
    49: "Wishing you a fun day filled with love and laughter!",
    50: "Hope you have a day full of exciting moments and joy!",
    51: "Wishing you peace, love, and smiles for today and always!",
    52: "Have a day as wonderful as you are!",
    53: "May today surprise you with all the happiness you deserve!",
    54: "Here’s to a day full of joy, smiles, and good times!",
    55: "Take a moment to smile and enjoy today’s journey!",
    56: "Wishing you a day full of laughter and beautiful surprises!",
    57: "Here’s to a day filled with peace, love, and positivity!",
    58: "Hope today is as bright and joyful as your spirit!",
    59: "May your day be filled with good company and laughter!",
    60: "Wishing you a day full of love, smiles, and fun!",
    61: "Here’s to a day that’s as wonderful as you are!",
    62: "May today be filled with love, light, and laughter!",
    63: "Wishing you a day full of sunshine and smiles!",
    64: "Hope you have a great day full of fun and good vibes!",
    65: "May your day be as bright as your smile!",
    66: "Sending you all the happiness for a joyful day!",
    67: "Wishing you peace and joy for a calm and happy day!",
    68: "Here’s to a day full of laughter, love, and light!",
    69: "Hope today brings you beautiful surprises and lots of fun!",
    70: "Wishing you a wonderful day filled with happiness and joy!",
    71: "May today be full of peace, love, and laughter!",
    72: "Have an awesome day, full of fun and smiles!",
    73: "Wishing you a peaceful and joyful day ahead!",
    74: "Hope your day is filled with lots of little joys and big smiles!",
    75: "Here’s to a bright and beautiful day full of love!",
    76: "May today bring you all the joy and happiness you deserve!",
    77: "Wishing you a fun-filled day full of laughter and smiles!",
    78: "Hope you have a wonderful day filled with peace and joy!",
    79: "Here’s to a day of happiness, laughter, and good times!",
    80: "Wishing you a bright and cheerful day filled with love!",
    81: "May your day be full of smiles and joyful moments!",
    82: "Hope today is full of positivity and happiness for you!",
    83: "Wishing you a wonderful day full of good vibes!",
    84: "May today bring you love, peace, and endless smiles!",
    85: "Hope you have an amazing day filled with happiness and joy!",
    86: "Wishing you a fun day full of laughter and good times!",
    87: "Here’s to a day full of peace, love, and light!",
    88: "May today be as joyful and wonderful as you are!",
    89: "Wishing you a beautiful day full of happiness and peace!",
    90: "Hope you have a great day filled with good moments and smiles!",
    91: "May your day be filled with love, laughter, and positivity!",
    92: "Wishing you all the joy and happiness for a great day ahead!",
    93: "Hope today brings you fun and good times all around!",
    94: "Wishing you a joyful day filled with love and peace!",
    95: "May your day be bright and filled with positive energy!",
    96: "Hope you have a fantastic day full of smiles and joy!",
    97: "Wishing you peace, love, and happiness today and always!",
    98: "May today bring you endless joy and wonderful moments!",
    99: "Here’s to a day full of good vibes and great times!",
    100: "Wishing you a fun and cheerful day filled with love!",
    101: "Wishing you a bright day filled with happiness and hope!",
    102: "May your day be filled with positive thoughts and good energy!",
    103: "Here’s to a day of success, joy, and laughter!",
    104: "Hope today brings you new opportunities and happiness!",
    105: "Wishing you a day full of kindness, love, and peace!",
    106: "May your day be as sweet as you are!",
    107: "Have a fantastic day filled with excitement and good moments!",
    108: "Here’s to a day that’s just as wonderful as you!",
    109: "Wishing you a day full of love, smiles, and good vibes!",
    110: "Hope today surprises you with lots of happiness and laughter!",
    111: "May today be the start of something great!",
    112: "Sending you lots of love for a beautiful day ahead!",
    113: "Wishing you a peaceful day with moments that make you smile!",
    114: "Here’s to a day that brings you closer to your dreams!",
    115: "Hope today is full of adventure and new experiences!",
    116: "Wishing you a day of calm, peace, and good energy!",
    117: "May your day be filled with all the things you love!",
    118: "Here’s to a happy day that leaves you feeling grateful!",
    119: "Wishing you joy and laughter that lights up your day!",
    120: "Hope today is full of magical moments and happy surprises!",
    121: "May today be bright and bring you closer to your goals!",
    122: "Wishing you a productive day full of good things!",
    123: "Here’s to a day that feels light and joyful!",
    124: "Hope you have a peaceful day filled with smiles and warmth!",
    125: "May today bring you fresh inspiration and positive thoughts!",
    126: "Wishing you a day full of kindness and thoughtful moments!",
    127: "Here’s to a day that’s easygoing and fun-filled!",
    128: "Hope your day is sprinkled with little bits of joy!",
    129: "May today be a day of peace, relaxation, and happiness!",
    130: "Wishing you a bright and successful day ahead!",
    131: "Hope today fills your heart with joy and your mind with peace!",
    132: "May today be a day where good things come your way!",
    133: "Here’s to a day of laughter, light, and good energy!",
    134: "Wishing you a lovely day full of sunshine and smiles!",
    135: "Hope today brings you fun, laughter, and positivity!",
    136: "May your day be filled with warmth, light, and happiness!",
    137: "Wishing you a peaceful day full of calm and good energy!",
    138: "Here’s to a day that brings you closer to your dreams!",
    139: "Hope today fills your heart with gratitude and joy!",
    140: "May your day be bright and your worries light!",
    141: "Wishing you a happy day full of smiles and fun!",
    142: "Hope today is full of little joys and big moments of peace!",
    143: "May your day be as sunny as the smile on your face!",
    144: "Wishing you a calm and productive day ahead!",
    145: "Here’s to a joyful day filled with love and positive vibes!",
    146: "Hope today brings you the peace and calm you need!",
    147: "Wishing you a successful and fulfilling day ahead!",
    148: "May your day be sprinkled with happiness and good times!",
    149: "Hope today brings you lots of smiles and exciting moments!",
    150: "Wishing you a day of peace, joy, and a little bit of magic!",
    151: "May today be full of possibilities and positive energy!",
    152: "Hope you have a day full of laughter and great memories!",
    153: "Wishing you a bright and cheerful day filled with kindness!",
    154: "May today bring you peace, love, and lighthearted joy!",
    155: "Hope today is filled with uplifting energy and good surprises!",
    156: "Wishing you a day that’s as positive as your spirit!",
    157: "Here’s to a fun-filled day with plenty of reasons to smile!",
    158: "Hope today gives you a fresh perspective and clear mind!",
    159: "Wishing you a day filled with small victories and big smiles!",
    160: "May your day be peaceful, productive, and full of joy!",
    161: "Hope today is full of moments that make your heart happy!",
    162: "Wishing you a relaxing day full of calm and contentment!",
    163: "May today surprise you with unexpected happiness!",
    164: "Hope your day is filled with positivity and good fortune!",
    165: "Wishing you a day full of laughter, joy, and new memories!",
    166: "May today be as wonderful and unique as you are!",
    167: "Hope today brings you excitement and endless smiles!",
    168: "Wishing you a day where everything just flows perfectly!",
    169: "May today be a day of clarity, calm, and success!",
    170: "Here’s to a day of positivity and amazing possibilities!",
    171: "Hope today brings you peace, joy, and lighthearted fun!",
    172: "Wishing you a productive and cheerful day ahead!",
    173: "May today be full of smiles, laughter, and little wins!",
    174: "Hope today leaves you feeling light, happy, and inspired!",
    175: "Wishing you a day that’s full of bright moments and joy!",
    176: "May your day be filled with creativity, fun, and peace!",
    177: "Hope today is full of moments that make you truly happy!",
    178: "Wishing you a day of relaxation and inner peace!",
    179: "May today be as bright and wonderful as you are!",
    180: "Hope your day is full of good news and happy surprises!",
    181: "Wishing you a day full of laughter and lighthearted fun!",
    182: "May today bring you happiness in all the little things!",
    183: "Hope today is filled with joy, laughter, and peace!",
    184: "Wishing you a day of calm energy and beautiful moments!",
    185: "May your day be productive, peaceful, and happy!",
    186: "Hope today is filled with love, good vibes, and success!",
    187: "Wishing you a day of clarity, joy, and achievement!",
    188: "May today be full of inspiration, kindness, and smiles!",
    189: "Hope you have a joyful day with plenty of time to relax!",
    190: "Wishing you a day full of love, light, and endless positivity!",
    191: "May today surprise you with something exciting and new!",
    192: "Hope today is filled with laughter and unforgettable moments!",
    193: "Wishing you a day of warmth, happiness, and light!",
    194: "May today bring you plenty of reasons to smile and feel good!",
    195: "Hope today is a mix of fun, peace, and happy surprises!",
    196: "Wishing you a day of peaceful thoughts and kind gestures!",
    197: "May today be filled with good energy and joyful experiences!",
    198: "Hope your day is full of beautiful moments and exciting news!",
    199: "Wishing you a day where everything just falls into place!",
    200: "May today bring you all the good things you’ve been waiting for!",
    201: "Hope today is full of laughter, kindness, and positivity!",
    202: "Wishing you a joyful day that brings you closer to your dreams!",
    203: "May your day be filled with good news, smiles, and success!",
    204: "Hope today surprises you with happiness and good luck!",
    205: "Wishing you a peaceful and productive day full of love!",
    206: "May today be a day of joy, creativity, and bright moments!",
    207: "Hope today gives you the space to breathe, relax, and smile!",
    208: "Wishing you a beautiful day of calm and happy surprises!",
    209: "May today bring you joy, peace, and unexpected blessings!",
    210: "Hope you have a day filled with laughter and wonderful news!",
    211: "Wishing you a day filled with laughter, love, and success!",
    212: "Hope today brings you a fresh start and endless opportunities!",
    213: "May your day be full of positive thoughts and happy moments!",
    214: "Wishing you a day that’s as bright and joyful as you deserve!",
    215: "Hope today fills your heart with joy and peace!",
    216: "May today bring you closer to the dreams you’re chasing!",
    217: "Wishing you a peaceful day filled with small, happy surprises!",
    218: "Hope your day is full of sunshine, smiles, and good fortune!",
    219: "May today be a day of great progress and little victories!",
    220: "Wishing you a wonderful day filled with kindness and joy!",
    221: "Hope today is as beautiful and fulfilling as you want it to be!",
    222: "May today bring you clarity, creativity, and positive vibes!",
    223: "Wishing you a joyful day full of laughter and fun adventures!",
    224: "Hope today brings you light, love, and happy surprises!",
    225: "May your day be full of moments that make you feel alive and joyful!",
    226: "Wishing you a day where everything works out perfectly!",
    227: "Hope today fills your heart with gratitude and your mind with peace!",
    228: "May today bring you inspiration, joy, and exciting new experiences!",
    229: "Wishing you a day that’s filled with smiles and endless possibilities!",
    230: "Hope today is the beginning of something amazing for you!",
    231: "May today be a day of relaxation, happiness, and creativity!",
    232: "Wishing you a peaceful day full of good news and happy moments!",
    233: "Hope your day is full of joy and little things that make you smile!",
    234: "May today bring you success, laughter, and new adventures!",
    235: "Wishing you a bright day filled with love and positive energy!",
    236: "Hope today is full of exciting opportunities and peaceful moments!",
    237: "May today be filled with positive thoughts and wonderful surprises!",
    238: "Wishing you a day of peace, happiness, and unexpected joy!",
    239: "Hope today is filled with success, smiles, and lots of love!",
    240: "May your day be full of clarity, calm, and joyful experiences!",
    241: "Wishing you a beautiful day full of love, light, and peace!",
    242: "Hope today is as amazing as you are, full of joy and love!",
    243: "May today bring you the peace and happiness you seek!",
    244: "Wishing you a day of relaxation, fun, and positive energy!",
    245: "Hope today is full of wonderful surprises and happy moments!",
    246: "May today be a day of laughter, joy, and new beginnings!",
    247: "Wishing you a productive day full of good news and happy vibes!",
    248: "Hope today brings you peace, clarity, and a little bit of magic!",
    249: "May today be full of smiles, positive thoughts, and great memories!",
    250: "Wishing you a peaceful and relaxing day full of good energy!",
    251: "Hope today brings you joy, peace, and exciting new opportunities!",
    252: "May today be a day of calm, success, and happiness!",
    253: "Wishing you a day full of smiles, laughter, and good fortune!",
    254: "Hope your day is filled with beautiful moments and happy surprises!",
    255: "May today bring you peace, joy, and lots of positive energy!",
    256: "Wishing you a day that’s as bright and joyful as you!",
    257: "Hope today is full of laughter, love, and fun adventures!",
    258: "May today be a day of peace, relaxation, and endless possibilities!",
    259: "Wishing you a beautiful day full of joy, light, and love!",
    260: "Hope today is as wonderful as you are, full of smiles and happiness!",
    261: "May today bring you the happiness and peace you deserve!",
    262: "Wishing you a day of joy, calm, and happy moments!",
    263: "Hope today is full of exciting new experiences and little surprises!",
    264: "May your day be filled with laughter, love, and good energy!",
    265: "Wishing you a peaceful day full of good news and positive vibes!",
    266: "Hope today brings you success, clarity, and joy!",
    267: "May today be full of smiles, peace, and happy moments!",
    268: "Wishing you a day of light, love, and endless possibilities!",
    269: "Hope today surprises you with good things and happy moments!",
    270: "May today be a day of peace, joy, and laughter!",
    271: "Wishing you a day filled with beautiful moments and positive thoughts!",
    272: "Hope today brings you happiness, peace, and plenty of smiles!",
    273: "May today be a day of relaxation, joy, and little victories!",
    274: "Wishing you a day full of love, light, and peace!",
    275: "Hope your day is filled with fun, excitement, and happy surprises!",
    276: "May today bring you peace, success, and positive energy!",
    277: "Wishing you a beautiful day full of smiles and happy moments!",
    278: "Hope today is full of joy, laughter, and new opportunities!",
    279: "May today be a day of calm, success, and endless happiness!",
    280: "Wishing you a peaceful day filled with positive energy and love!",
    281: "Hope today surprises you with good things and joyful moments!",
    282: "May today bring you the peace, joy, and happiness you seek!",
    283: "Wishing you a day of clarity, success, and positivity!",
    284: "Hope today is full of smiles, laughter, and beautiful moments!",
    285: "May today be a day of fun, peace, and little surprises!",
    286: "Wishing you a day filled with joy, calm, and good energy!",
    287: "Hope today brings you success, peace, and plenty of smiles!",
    288: "May today be full of wonderful surprises and happy moments!",
    289: "Wishing you a bright day filled with love and positive vibes!",
    290: "Hope today is full of light, joy, and new adventures!",
    291: "May today bring you peace, happiness, and plenty of smiles!",
    292: "Wishing you a beautiful day full of joy, peace, and love!",
    293: "Hope today is filled with good news and happy surprises!",
    294: "May today bring you success, laughter, and new opportunities!",
    295: "Wishing you a peaceful day filled with positivity and good energy!",
    296: "Hope today is full of love, joy, and exciting new experiences!",
    297: "May today be a day of clarity, calm, and happiness!",
    298: "Wishing you a bright day filled with smiles and positive thoughts!",
    299: "Hope today is full of beautiful moments and unexpected surprises!",
    300: "May today bring you peace, happiness, and lots of joy!",
    301: "Wishing you a joyful day filled with laughter and good vibes!",
    302: "Hope today surprises you with happiness and new opportunities!",
    303: "May today bring you clarity, peace, and little victories!",
    304: "Wishing you a beautiful day filled with love and positivity!",
    305: "Hope today is full of fun, laughter, and new experiences!",
    306: "May today be a day of peace, success, and joyful moments!",
    307: "Wishing you a peaceful day full of good news and happiness!",
    308: "Hope today brings you smiles, laughter, and good fortune!",
    309: "May today be filled with love, joy, and plenty of happy moments!",
    310: "Wishing you a bright day filled with exciting new possibilities!",
    311: "Hope today surprises you with joy, peace, and little victories!",
    312: "May today be a day of calm, laughter, and happiness!",
    313: "Wishing you a day full of light, love, and positive energy!",
    314: "Hope today is full of fun, peace, and happy surprises!",
    315: "May today bring you success, joy, and new opportunities!",
    316: "Wishing you a joyful day filled with good news and plenty of smiles!",
    317: "Hope today is full of wonderful surprises and positive energy!",
    318: "May today bring you peace, clarity, and moments of joy!",
    319: "Wishing you a bright day filled with good news and happiness!",
    320: "Hope today brings you success, laughter, and lots of love!",
    321: "May today be a day of fun, peace, and exciting new adventures!",
    322: "Wishing you a peaceful day filled with good energy and joy!",
    323: "Hope today brings you plenty of smiles and happy surprises!",
    324: "May today be a day of peace, joy, and little victories!",
    325: "Wishing you a bright and joyful day filled with laughter!",
    326: "Hope today is full of exciting new experiences and positive vibes!",
    327: "May today bring you clarity, calm, and plenty of happiness!",
    328: "Wishing you a peaceful day filled with smiles and laughter!",
    329: "Hope today surprises you with good news and happy moments!",
    330: "May today be a day of peace, love, and exciting new opportunities!",
    331: "Wishing you a day filled with joy, happiness, and plenty of fun!",
    332: "Hope today is full of wonderful moments and happy surprises!",
    333: "May today bring you success, peace, and positive energy!",
    334: "Wishing you a bright day filled with smiles and love!",
    335: "Hope today surprises you with new adventures and joyful moments!",
    336: "May today be a day of peace, success, and little victories!",
    337: "Wishing you a day full of joy, light, and positivity!",
    338: "Hope today brings you calm, peace, and wonderful experiences!",
    339: "May today be a day of laughter, joy, and good fortune!",
    340: "Wishing you a peaceful day filled with love and exciting opportunities!",
    341: "Hope today surprises you with happy moments and little victories!",
    342: "May today be full of clarity, calm, and exciting new experiences!",
    343: "Wishing you a bright day filled with joy, love, and laughter!",
    344: "Hope today is filled with exciting opportunities and positive vibes!",
    345: "May today bring you success, peace, and lots of love!",
    346: "Wishing you a peaceful day filled with good news and happy surprises!",
    347: "Hope today is full of smiles, joy, and wonderful experiences!",
    348: "May today bring you happiness, success, and new adventures!",
    349: "Wishing you a bright day full of positivity and little victories!",
    350: "Hope today surprises you with new opportunities and good news!",
    351: "May today be a day of peace, joy, and plenty of smiles!",
    352: "Wishing you a day full of light, love, and positive energy!",
    353: "Hope today is full of wonderful surprises and exciting new experiences!",
    354: "May today bring you success, happiness, and lots of love!",
    355: "Wishing you a bright and joyful day filled with exciting new adventures!",
    356: "Hope today brings you peace, joy, and positive energy!",
    357: "May today be a day of clarity, calm, and little victories!",
    358: "Wishing you a peaceful day full of smiles, love, and good news!",
    359: "Hope today surprises you with new opportunities and joyful moments!",
    360: "May today be a day full of happiness, success, and good fortune!",
    361: "Wishing you a bright day filled with laughter, light, and love!",
    362: "Hope today brings you peace, joy, and plenty of positive energy!",
    363: "May today be a day of exciting new adventures and happy moments!",
    364: "Wishing you a day filled with love, light, and laughter!",
    365: "Hope today surprises you with joy, peace, and good news!",
    366: "May today be full of little victories and exciting opportunities!",
    367: "Wishing you a peaceful day filled with positive thoughts and happiness!",
    368: "Hope today is full of smiles, laughter, and wonderful surprises!",
    369: "May today bring you success, joy, and good fortune!",
    370: "Wishing you a bright day filled with exciting new experiences!",
    371: "Hope today brings you clarity, calm, and positive energy!",
    372: "May today be a day of love, peace, and happiness!",
    373: "Wishing you a joyful day full of laughter and wonderful moments!",
    374: "Hope today surprises you with new opportunities and joyful experiences!",
    375: "May today bring you success, joy, and lots of love!",
    376: "Wishing you a peaceful day filled with smiles and positive thoughts!",
    377: "Hope today is full of exciting new opportunities and good news!",
    378: "May today be a day of clarity, peace, and happy moments!",
    379: "Wishing you a bright day full of positivity and love!",
    380: "Hope today surprises you with exciting adventures and joyful moments!",
    381: "May today bring you success, happiness, and lots of fun!",
    382: "Wishing you a peaceful day filled with good energy and happy surprises!",
    383: "Hope today brings you plenty of smiles, laughter, and love!",
    384: "May today be a day of clarity, calm, and new adventures!",
    385: "Wishing you a joyful day filled with love, peace, and happiness!",
    386: "Hope today surprises you with good fortune and exciting opportunities!",
    387: "May today be a day full of laughter, joy, and positive energy!",
    388: "Wishing you a peaceful day full of good news and happiness!",
    389: "Hope today brings you new adventures, smiles, and lots of love!",
    390: "May today be a day of success, peace, and happy moments!",
    391: "Wishing you a bright day filled with positivity and good energy!",
    392: "Hope today is full of exciting new opportunities and joyful experiences!",
    393: "May today bring you happiness, clarity, and little victories!",
    394: "Wishing you a joyful day filled with laughter and positive energy!",
    395: "Hope today surprises you with good fortune and new opportunities!",
    396: "May today be full of smiles, peace, and happy moments!",
    397: "Wishing you a peaceful day filled with love, light, and joy!",
    398: "Hope today brings you success, laughter, and new adventures!",
    399: "May today be a day full of joy, peace, and good fortune!",
    400: "Wishing you a bright day filled with happiness and exciting opportunities!"
};


