export const playlistAuthorMap: { [key: string]: string } = {
    "Diogo Pinto": "Diogo Pinto",
    "Ana Serra Do Norte": "Ana",
    "Mariana Machete": "Maria Machete",
    "Pedro Afonso": "Pedro Afonso",
    "andrefncunha": "André",
    "cheesymike505": "Miguel",
    "danielaramalhom": "Dani",
    "Ricardo Branco": "Ricardo Branco",
    "Luísa Andrade": "Luísa Andrade",
    "Catarina Baptista": "Catarina Baptista",
    "xgugax": "Gustavo",
    "diogoesilva41": "Diogo E Silva",
    "beatriz24699": "Beatriz Caetano",
    "Rui Pedro Carvalho": "Rui Cromi",
    "pitosgagamer": "Tomás",
    "Bernardo Caetano": "Bernardo",
    "Joaninha": "Joaninha",
    "Fred": "Fred"
};
